# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cv.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.study = QtWidgets.QTabWidget(self.centralwidget)
        self.study.setGeometry(QtCore.QRect(49, 9, 701, 521))
        self.study.setStyleSheet("color: rgb(0, 0, 0);")
        self.study.setObjectName("study")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(30, 30, 115, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(150, 10, 261, 61))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.param_bin = QtWidgets.QLineEdit(self.page_3)
        self.param_bin.setGeometry(QtCore.QRect(10, 20, 115, 30))
        self.param_bin.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_bin.setText("")
        self.param_bin.setObjectName("param_bin")
        self.stackedWidget.addWidget(self.page_3)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.param_p = QtWidgets.QLineEdit(self.page_7)
        self.param_p.setGeometry(QtCore.QRect(10, 20, 115, 30))
        self.param_p.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_p.setText("")
        self.param_p.setObjectName("param_p")
        self.param_q = QtWidgets.QLineEdit(self.page_7)
        self.param_q.setGeometry(QtCore.QRect(140, 20, 115, 30))
        self.param_q.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_q.setText("")
        self.param_q.setObjectName("param_q")
        self.stackedWidget.addWidget(self.page_7)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.param_pq = QtWidgets.QLineEdit(self.page_4)
        self.param_pq.setGeometry(QtCore.QRect(10, 20, 115, 30))
        self.param_pq.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_pq.setText("")
        self.param_pq.setObjectName("param_pq")
        self.stackedWidget.addWidget(self.page_4)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.param_scale = QtWidgets.QLineEdit(self.page)
        self.param_scale.setGeometry(QtCore.QRect(10, 20, 115, 30))
        self.param_scale.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_scale.setText("")
        self.param_scale.setObjectName("param_scale")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.param_w = QtWidgets.QLineEdit(self.page_2)
        self.param_w.setGeometry(QtCore.QRect(10, 20, 115, 30))
        self.param_w.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_w.setText("")
        self.param_w.setClearButtonEnabled(False)
        self.param_w.setObjectName("param_w")
        self.stackedWidget.addWidget(self.page_2)
        self.resultButton = QtWidgets.QPushButton(self.tab)
        self.resultButton.setEnabled(True)
        self.resultButton.setGeometry(QtCore.QRect(290, 100, 115, 30))
        self.resultButton.setStyleSheet("background-color: rgb(170, 170, 170);\n"
"color: rgb(130, 130, 130);")
        self.resultButton.setCheckable(False)
        self.resultButton.setAutoDefault(True)
        self.resultButton.setDefault(False)
        self.resultButton.setObjectName("resultButton")
        self.selectedImage = QtWidgets.QLabel(self.tab)
        self.selectedImage.setGeometry(QtCore.QRect(30, 160, 182, 191))
        self.selectedImage.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.selectedImage.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedImage.setObjectName("selectedImage")
        self.selectedImage_2 = QtWidgets.QLabel(self.tab)
        self.selectedImage_2.setGeometry(QtCore.QRect(230, 160, 182, 191))
        self.selectedImage_2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.selectedImage_2.setAlignment(QtCore.Qt.AlignCenter)
        self.selectedImage_2.setObjectName("selectedImage_2")
        self.param_class = QtWidgets.QLineEdit(self.tab)
        self.param_class.setGeometry(QtCore.QRect(30, 100, 115, 30))
        self.param_class.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_class.setObjectName("param_class")
        self.param_photo = QtWidgets.QLineEdit(self.tab)
        self.param_photo.setGeometry(QtCore.QRect(160, 100, 115, 30))
        self.param_photo.setStyleSheet("background-color: rgb(190, 190, 190);\n"
"padding-left: 10px;")
        self.param_photo.setObjectName("param_photo")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 80, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(160, 80, 60, 16))
        self.label_2.setObjectName("label_2")
        self.study.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.study.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.study.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "HIstogram"))
        self.comboBox.setItemText(1, _translate("MainWindow", "DFT"))
        self.comboBox.setItemText(2, _translate("MainWindow", "DCT"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Scale"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Gradient"))
        self.param_bin.setPlaceholderText(_translate("MainWindow", "Enter BIN"))
        self.param_p.setPlaceholderText(_translate("MainWindow", "Enter P"))
        self.param_q.setPlaceholderText(_translate("MainWindow", "Enter Q"))
        self.param_pq.setPlaceholderText(_translate("MainWindow", "Enter P/Q"))
        self.param_scale.setPlaceholderText(_translate("MainWindow", "Enter Scale"))
        self.param_w.setPlaceholderText(_translate("MainWindow", "Enter W"))
        self.resultButton.setText(_translate("MainWindow", "Find"))
        self.selectedImage.setText(_translate("MainWindow", "Selected Image"))
        self.selectedImage_2.setText(_translate("MainWindow", "Selected Image"))
        self.param_class.setText(_translate("MainWindow", "1"))
        self.param_class.setPlaceholderText(_translate("MainWindow", "Enter № Class"))
        self.param_photo.setText(_translate("MainWindow", "1"))
        self.param_photo.setPlaceholderText(_translate("MainWindow", "Enter № Photo"))
        self.label.setText(_translate("MainWindow", "Class"))
        self.label_2.setText(_translate("MainWindow", "Photo"))
        self.study.setTabText(self.study.indexOf(self.tab), _translate("MainWindow", "Эксперимент"))
        self.study.setTabText(self.study.indexOf(self.tab_2), _translate("MainWindow", "Исследование"))

